### ISSUE TITLE
blender script import csv

### ISSUE THREAD

**Issue by webbyeasy** [sbobovyc/GameTools#10]
Hi There, I am able to successfully import a CSV from renderdoc and import into blender, however the model is squashed / scaled non uniformly, is there something I am doing wrong?

thank you.

**Comment by webbyeasy** [comment]
doing a bit of scaling and comparing, it looks like the scale factor in blender is
x=1
y=.5
z=4

Might be a bounding box thing? But the model looks fine in renderdoc mesh preview.

**Comment by webbyeasy** [comment]
no I made sure to use vs in, the model looks correct in renderdoc. I have a feeling its to do with my screens aspect ratio?

**Comment by webbyeasy** [comment]
sorry I didnt save the renderdoc file, but here is the raw CSV from exporting VS IN, 
Its a 20mm cube.
[cuberaw1.zip](https://github.com/sbobovyc/GameTools/files/2400549/cuberaw1.zip)

**Comment by sbobovyc** [comment]
I don't see any formatting issues with the CSV, but without the renderdoc I can't do much to help.

**Comment by webbyeasy** [comment]
When you print he cube into blender using your script, it is skewed or correct? mine is skewed.

**Comment by sbobovyc** [comment]
It's skewed, but I can't tell you why. Can you do another capture?
