### ISSUE TITLE
import_pix.py to blender 2.8

### ISSUE THREAD

**Issue by koloved** [sbobovyc/GameTools#11]
How to update it?

**Comment by sbobovyc** [comment]
You are better off converting from csv to obj using this https://github.com/sbobovyc/GameTools/blob/master/common/raw2obj.py

**Comment by friuns2** [comment]
raw2obj.py didn't work either for me, i click import its says modules installed ()
but there no import added

**Comment by sbobovyc** [comment]
raw2obj.py is not a blender plugin, it is a stand alone command line tool

**Comment by stormloop** [comment]
how do you then use it? if i open it it just closes itself again

**Comment by sbobovyc** [comment]
@stormloop What OS are you using?

**Comment by stormloop** [comment]
Windows 10

**Comment by stormloop** [comment]
do i need a special python thing to run it?

**Comment by sbobovyc** [comment]
Python 3, nothing special

**Comment by stormloop** [comment]
well i have 3.8.1, i guess that works too

**Comment by stormloop** [comment]
when i do what you said it gives me:
>>> python3 raw2obj.py -h
  File "<stdin>", line 1
    python3 raw2obj.py -h
                  ^
SyntaxError: invalid syntax

**Comment by stormloop** [comment]
the ^is under the r from raw2obj.py

**Comment by sbobovyc** [comment]
How did you download raw2obj.py? Did you click on "Raw" button and then save as text file?

**Comment by stormloop** [comment]
is that the way to do it?

**Comment by sbobovyc** [comment]
Another is to clone or download the entire repo. If you just want that script, raw is fine.

**Comment by stormloop** [comment]
then yes it still does that, but dont you need to pase a file path? not just a file name

**Comment by sbobovyc** [comment]
You can either pass the full path to where the script is like:
python3 C:\Users\sbobovyc\Desktop\raw2obj.py -h
or you can change directory to where the script is and run it there:
cd C:\Users\sbobovyc\Desktop
python3 raw2obj.py -h

**Comment by stormloop** [comment]
it gives the same error for that that it gave for actually trying to run the command
the cd one

**Comment by sbobovyc** [comment]
Can you post a screen shot of exactly what you are doing?

**Comment by stormloop** [comment]
sorry for late answer, i was quite busy the past few days...
![raw2obj](https://user-images.githubusercontent.com/52413267/82191097-4e37aa80-98f2-11ea-9386-da277f052a8f.PNG)

**Comment by sbobovyc** [comment]
You are executing a shell command on the python shell. Instead of starting a python shell, use cmd (Command Prompt) or PowerShell.
![image](https://user-images.githubusercontent.com/704069/82235500-c3aa7780-9900-11ea-8f0c-0d962fb950d4.png)

**Comment by stormloop** [comment]
i feel  kinda stupid, but this is now in cmd (its just in dutch), -h doesnt seem to do much
![raw2objcmnd](https://user-images.githubusercontent.com/52413267/82254197-b1592980-9952-11ea-89e8-e936c895476a.PNG)

**Comment by sbobovyc** [comment]
Let's see if your python path is set. Try this:
![image](https://user-images.githubusercontent.com/704069/82283573-c76fe580-9964-11ea-9f39-a376c09d4eb9.png)

**Comment by stormloop** [comment]
does nothing, so i guess its not set, how do i set it? also sorry for the amount of questions, kinda  new to this

**Comment by stormloop** [comment]
ok i followed the internet and now my path should be set, python --version still doesnt do anything but python3 redirects me to the download page of python3.8 in de microsoft store, i downloaded it and path is linked, so i tried the help command again but now i get this:
![-h](https://user-images.githubusercontent.com/52413267/82301894-29f2d100-99b9-11ea-98c3-5618c4388f9f.PNG)

**Comment by sbobovyc** [comment]
You are getting closer. You need to install the pandas module. If that version of python came with pip (pip3), you can use that to install it.
```
pip3 install pandas
```

**Comment by stormloop** [comment]
i installed, but couldnt type again after, started new cmd and got the same error

**Comment by sbobovyc** [comment]
Did pip install not complete? If that's the case, then pandas module did not get installed and that explains the error.

**Comment by stormloop** [comment]
ok now it worked, i was a little too quick with closing cmd it seems, i am having difficulties understanding how to use it, english isnt my first language after all...

**Comment by sbobovyc** [comment]
It's a bit of a Swiss army knife, so I can't really sum it up for you. Do you have an object you are trying to convert to obj?

**Comment by stormloop** [comment]
i do, but cant acces my pc atm, essentially i am trying to get models from elite dangerous ships, so the one i'll send wont be a full ship as thats the restrictions on renderdoc or tje csv file format

**Comment by stormloop** [comment]
here is what i am trying to convert atm:
[Anaconda.zip](https://github.com/sbobovyc/GameTools/files/4656071/Anaconda.zip)

**Comment by sbobovyc** [comment]
I think you grabbed the projected version of the model. Can you share the renderdoc file?

**Comment by sbobovyc** [comment]
Also, I found a bug in the script, so download the latest version.

**Comment by stormloop** [comment]
ill share in a few hours, why do you need the renderdoc and not the csv though? doesnt the csv contain all points etc.?

**Comment by stormloop** [comment]
http://www.mediafire.com/file/12kth01wulfqf7v/CaptureAnaconda.zip/file
this is the link to the renderdoc, it was too big to just embed...

**Comment by sbobovyc** [comment]
Take a look at this.
https://stan-bobovych.com/blog/using-raw2obj-py-part-1

**Comment by stormloop** [comment]
ok

**Comment by stormloop** [comment]
lmao did you make that page just now with the renderdoc i provided? thanks...

**Comment by stormloop** [comment]
ok so... if only IDX and position columns are important, what do you do with the rest? or do you just do -position and it takes care of it yourself?

**Comment by stormloop** [comment]
and it works, thank you very much, i honestly have no idea how you didn't give up yet, i know i asked a lot of stupid questions and still you managed to make it work... thank you very much.

**Comment by sbobovyc** [comment]
No problem. I did not expect that many people to get a hold of that script, so I never wrote up any documentation. Keep on experimenting with it and if you have any questions submit another issue.
