### ISSUE TITLE
renderdoc vertex limit

### ISSUE THREAD

**Issue by stormloop** [sbobovyc/GameTools#12]
so this is not the place to ask this and i know it isn't, but you seem to know some stuff and i don't know where else to ask, renderdoc has a vertex limit so big ships cant be exported fully in one piece, so i thought about doing a capture from another angle but silly me it doesn't work, i get the exact same model because i am trying to capture the same thing twice (duhh), do you know of a way to overwrite the limit/ get other vertexes captured. normally it isn't a problem as the ships are symmetrical so i just mirrored it in blender but there is a little bit at the back where there are holes.

**Comment by stormloop** [comment]
also is there another way for me to ask your help outside of opening new  tickets all the time?

**Comment by sbobovyc** [comment]
I was not aware that there is a limit to the number of vertices renderdoc shows. Can you post a screenshot showing the draw command?
