### ISSUE TITLE
error when installing PIX CSV on Blender 2.79

### ISSUE THREAD

**Issue by FelixHappyGamer** [sbobovyc/GameTools#14]
(I think it might be the version) Whenever I install the PIX CSV addon on to blender, everything goes fine, but whenever I try to check the box to run it, I get this error.
![Captura de pantalla (4)](https://user-images.githubusercontent.com/71792978/94068919-b9851200-fde7-11ea-8bb1-b92eeddd2def.png)
Does anyone know if I have to do anything?

**Comment by sbobovyc** [comment]
That plugin got bumped to Blender 2.80 and is no longer compatible with your version. You can check out an earlier version of the code at commit 3153264f18420e9527e365a3c9104446ecf539e4.
