### ISSUE TITLE
Vehicle model support

### ISSUE THREAD

**Issue by nercon** [sbobovyc/GameTools#3]
Really love the tool you made, however i found sadly that it does not support vehicles, and you hadn't have any update for over a year, are you planning on continue to finish this tool with more feature?

**Comment by sbobovyc** [comment]
Are you referring to Combat Mission vehicles?

**Comment by nercon** [comment]
yes, i'm referring to Combat Mission series, first time using Github, didn't know it is a global wise post

**Comment by sbobovyc** [comment]
I did not make a separate repository to CM tools, so you are fine. Do you have a particular use case for this feature?

**Comment by nercon** [comment]
I wanna create some better texture for CM vehile with Quixel DDO toolkit, the problem is in order to do so, DDO require the corresponding model to pre-render the texture, thus i've been looking for a solution to extract some vehicles out of mdr files.

**Comment by sbobovyc** [comment]
That's an interesting idea. Currently I am pretty busy with work, so I can't make any promises. Have you downloaded the scripts and tried them out on non-vehicle objects?
