### ISSUE TITLE
MoW Issue

### ISSUE THREAD

**Issue by MCiLuZiioNz** [sbobovyc/GameTools#4]
Having trouble trying to get the script to convert a character model.

Fails immediately outputting "Unsupported format".

**Comment by sbobovyc** [comment]
How about static meshes, such as weapons?

**Comment by MCiLuZiioNz** [comment]
Yes I saw that, it works fine for the most part, however it fails to import materials properly, UVs are never assigned to their proper vertex groups. I have to do it manually by hand, and based on reading your work, your script does seem to do it properly. Also may want to note your script has been updated more recently than the other one.

I know this may be a lot to ask, but any chance you could fork the other one and fix the UV/material issue. I created an issue there but have not gotten a reply.

**Comment by sbobovyc** [comment]
Looks like bjornmp  has responded to your ticket.
