### ISSUE TITLE
Having an issues importing csv file from Render Doc 0.30 into blender 2.77

### ISSUE THREAD

**Issue by superdave27** [sbobovyc/GameTools#6]
Below is the error I'm receiving in blender:

![screenshot 2016-09-03 11 58 14](https://cloud.githubusercontent.com/assets/6098686/18226743/cfb9ada6-71cd-11e6-8782-9961a25780d2.png)

**Comment by sbobovyc** [comment]
Can you give me the csv you are trying to import?

**Comment by superdave27** [comment]
I would not be surprised if it's the csv I generated.
[Python.zip](https://github.com/sbobovyc/GameTools/files/464794/Python.zip)

**Comment by sbobovyc** [comment]
Looks at the last few lines of the file. It contains a few rows with "-" where floating point numbers should be. The problem is with the csv exporter you are using.

**Comment by superdave27** [comment]
Thanks for taking the time to look into it.

**Comment by sbobovyc** [comment]
No problem!
