### ISSUE TITLE
import_pix.py bl_info causes issues

### ISSUE THREAD

**Issue by doakey3** [sbobovyc/GameTools#8]
A guy on the [blenderartists](https://blenderartists.org/forum/showthread.php?411379-CSV-model-importer&p=3125801&highlight=#post3125801) forum wanted to use your csv import function, but it wasn't working because of errors caused by the bl_info section on the addon. I made some corrections and put them into a pull request.

**Comment by sbobovyc** [comment]
Ok, thanks!
